apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-app2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: html-app2
  template:
    metadata:
      labels:
        app: html-app2
    spec:
      containers:
        - name: html-app2-container
          image: namespaxe/html-app:1.0.1
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
            limits:
              memory: "100Mi"
              cpu: "10m"
